-- Capstone vocabulary bank: 200 Spanish words the deck builder can draw from.
--
-- Run this AFTER capstone_schema.sql, in the Supabase SQL Editor for the project named by
-- SUPABASE_PROJECT_REF. It is idempotent -- re-running inserts nothing new.
--
-- Why a bank rather than letting the model invent words: a generated word can be a plausible
-- non-word, a false friend, or the wrong register. Picking from a fixed table makes the
-- agent's job selection rather than invention, and `lookup_spanish_word` stays as the check
-- on anything that does get through.
--
-- Accents are part of the spelling, not decoration: `ano` and `año` are different words, and
-- only one of them belongs on a flashcard for a child. Stored exactly as written.

create table if not exists public.vocabulary (
  id      bigint generated always as identity primary key,
  spanish text not null unique,
  english text not null,
  -- Topic the word belongs to, so a deck can be themed ("food", "family").
  subject text not null,
  level   text not null check (level in ('A1', 'A2', 'B1', 'B2', 'C1'))
);

create index if not exists vocabulary_level_idx   on public.vocabulary (level);
create index if not exists vocabulary_subject_idx on public.vocabulary (subject);

-- RLS on, no policies: unreachable via the anon key, reachable by the agent's access token.
alter table public.vocabulary enable row level security;

insert into public.vocabulary (spanish, english, subject, level) values
  ('hola', 'hello', 'greetings', 'A1'),
  ('adiós', 'goodbye', 'greetings', 'A1'),
  ('gracias', 'thank you', 'greetings', 'A1'),
  ('perdón', 'sorry, pardon', 'greetings', 'A1'),
  ('bienvenido', 'welcome', 'greetings', 'A2'),
  ('saludo', 'greeting', 'greetings', 'A2'),
  ('despedida', 'farewell', 'greetings', 'B1'),
  ('familia', 'family', 'family', 'A1'),
  ('madre', 'mother', 'family', 'A1'),
  ('padre', 'father', 'family', 'A1'),
  ('hermano', 'brother', 'family', 'A1'),
  ('hermana', 'sister', 'family', 'A1'),
  ('hijo', 'son', 'family', 'A1'),
  ('hija', 'daughter', 'family', 'A1'),
  ('abuelo', 'grandfather', 'family', 'A1'),
  ('abuela', 'grandmother', 'family', 'A1'),
  ('tío', 'uncle', 'family', 'A2'),
  ('tía', 'aunt', 'family', 'A2'),
  ('primo', 'cousin', 'family', 'A2'),
  ('esposo', 'husband', 'family', 'A2'),
  ('esposa', 'wife', 'family', 'A2'),
  ('sobrino', 'nephew', 'family', 'B1'),
  ('nieto', 'grandson', 'family', 'B1'),
  ('pan', 'bread', 'food', 'A1'),
  ('queso', 'cheese', 'food', 'A1'),
  ('carne', 'meat', 'food', 'A1'),
  ('pollo', 'chicken', 'food', 'A1'),
  ('pescado', 'fish (as food)', 'food', 'A1'),
  ('arroz', 'rice', 'food', 'A1'),
  ('huevo', 'egg', 'food', 'A1'),
  ('fruta', 'fruit', 'food', 'A1'),
  ('manzana', 'apple', 'food', 'A1'),
  ('naranja', 'orange (fruit)', 'food', 'A1'),
  ('plátano', 'banana', 'food', 'A1'),
  ('uva', 'grape', 'food', 'A2'),
  ('fresa', 'strawberry', 'food', 'A2'),
  ('verdura', 'vegetable', 'food', 'A2'),
  ('tomate', 'tomato', 'food', 'A1'),
  ('patata', 'potato', 'food', 'A1'),
  ('cebolla', 'onion', 'food', 'A2'),
  ('ajo', 'garlic', 'food', 'A2'),
  ('zanahoria', 'carrot', 'food', 'A2'),
  ('lechuga', 'lettuce', 'food', 'A2'),
  ('sal', 'salt', 'food', 'A1'),
  ('azúcar', 'sugar', 'food', 'A1'),
  ('aceite', 'oil', 'food', 'A2'),
  ('sopa', 'soup', 'food', 'A1'),
  ('postre', 'dessert', 'food', 'A2'),
  ('desayuno', 'breakfast', 'food', 'A1'),
  ('almuerzo', 'lunch', 'food', 'A1'),
  ('cena', 'dinner', 'food', 'A1'),
  ('agua', 'water', 'drink', 'A1'),
  ('leche', 'milk', 'drink', 'A1'),
  ('café', 'coffee', 'drink', 'A1'),
  ('vino', 'wine', 'drink', 'A1'),
  ('cerveza', 'beer', 'drink', 'A1'),
  ('zumo', 'juice', 'drink', 'A2'),
  ('refresco', 'soft drink', 'drink', 'A2'),
  ('perro', 'dog', 'animals', 'A1'),
  ('gato', 'cat', 'animals', 'A1'),
  ('caballo', 'horse', 'animals', 'A1'),
  ('vaca', 'cow', 'animals', 'A1'),
  ('cerdo', 'pig', 'animals', 'A2'),
  ('oveja', 'sheep', 'animals', 'A2'),
  ('pájaro', 'bird', 'animals', 'A1'),
  ('ratón', 'mouse', 'animals', 'A2'),
  ('conejo', 'rabbit', 'animals', 'A2'),
  ('oso', 'bear', 'animals', 'A2'),
  ('león', 'lion', 'animals', 'A2'),
  ('tigre', 'tiger', 'animals', 'A2'),
  ('elefante', 'elephant', 'animals', 'A2'),
  ('araña', 'spider', 'animals', 'B1'),
  ('abeja', 'bee', 'animals', 'B1'),
  ('rojo', 'red', 'colours', 'A1'),
  ('azul', 'blue', 'colours', 'A1'),
  ('verde', 'green', 'colours', 'A1'),
  ('amarillo', 'yellow', 'colours', 'A1'),
  ('negro', 'black', 'colours', 'A1'),
  ('blanco', 'white', 'colours', 'A1'),
  ('gris', 'grey', 'colours', 'A1'),
  ('marrón', 'brown', 'colours', 'A1'),
  ('rosado', 'pink', 'colours', 'A2'),
  ('morado', 'purple', 'colours', 'A2'),
  ('anaranjado', 'orange (colour)', 'colours', 'A2'),
  ('uno', 'one', 'numbers', 'A1'),
  ('dos', 'two', 'numbers', 'A1'),
  ('tres', 'three', 'numbers', 'A1'),
  ('cuatro', 'four', 'numbers', 'A1'),
  ('cinco', 'five', 'numbers', 'A1'),
  ('seis', 'six', 'numbers', 'A1'),
  ('siete', 'seven', 'numbers', 'A1'),
  ('ocho', 'eight', 'numbers', 'A1'),
  ('nueve', 'nine', 'numbers', 'A1'),
  ('diez', 'ten', 'numbers', 'A1'),
  ('veinte', 'twenty', 'numbers', 'A1'),
  ('mil', 'thousand', 'numbers', 'A2'),
  ('hora', 'hour', 'time', 'A1'),
  ('minuto', 'minute', 'time', 'A1'),
  ('día', 'day', 'time', 'A1'),
  ('semana', 'week', 'time', 'A1'),
  ('mes', 'month', 'time', 'A1'),
  ('año', 'year', 'time', 'A1'),
  ('hoy', 'today', 'time', 'A1'),
  ('mañana', 'tomorrow, morning', 'time', 'A1'),
  ('ayer', 'yesterday', 'time', 'A1'),
  ('noche', 'night', 'time', 'A1'),
  ('tarde', 'afternoon, late', 'time', 'A1'),
  ('lunes', 'Monday', 'calendar', 'A1'),
  ('martes', 'Tuesday', 'calendar', 'A1'),
  ('miércoles', 'Wednesday', 'calendar', 'A1'),
  ('jueves', 'Thursday', 'calendar', 'A1'),
  ('viernes', 'Friday', 'calendar', 'A1'),
  ('sábado', 'Saturday', 'calendar', 'A1'),
  ('domingo', 'Sunday', 'calendar', 'A1'),
  ('enero', 'January', 'calendar', 'A1'),
  ('febrero', 'February', 'calendar', 'A1'),
  ('marzo', 'March', 'calendar', 'A1'),
  ('abril', 'April', 'calendar', 'A1'),
  ('mayo', 'May', 'calendar', 'A1'),
  ('junio', 'June', 'calendar', 'A1'),
  ('julio', 'July', 'calendar', 'A1'),
  ('agosto', 'August', 'calendar', 'A1'),
  ('septiembre', 'September', 'calendar', 'A1'),
  ('octubre', 'October', 'calendar', 'A1'),
  ('noviembre', 'November', 'calendar', 'A1'),
  ('diciembre', 'December', 'calendar', 'A1'),
  ('cabeza', 'head', 'body', 'A1'),
  ('ojo', 'eye', 'body', 'A1'),
  ('nariz', 'nose', 'body', 'A1'),
  ('boca', 'mouth', 'body', 'A1'),
  ('oreja', 'ear', 'body', 'A1'),
  ('mano', 'hand', 'body', 'A1'),
  ('pie', 'foot', 'body', 'A1'),
  ('brazo', 'arm', 'body', 'A1'),
  ('pierna', 'leg', 'body', 'A1'),
  ('dedo', 'finger', 'body', 'A2'),
  ('pelo', 'hair', 'body', 'A1'),
  ('diente', 'tooth', 'body', 'A2'),
  ('corazón', 'heart', 'body', 'A2'),
  ('espalda', 'back', 'body', 'A2'),
  ('ropa', 'clothes', 'clothing', 'A1'),
  ('camisa', 'shirt', 'clothing', 'A1'),
  ('pantalón', 'trousers', 'clothing', 'A1'),
  ('falda', 'skirt', 'clothing', 'A2'),
  ('vestido', 'dress', 'clothing', 'A1'),
  ('zapato', 'shoe', 'clothing', 'A1'),
  ('sombrero', 'hat', 'clothing', 'A2'),
  ('abrigo', 'coat', 'clothing', 'A2'),
  ('calcetín', 'sock', 'clothing', 'A2'),
  ('chaqueta', 'jacket', 'clothing', 'A2'),
  ('casa', 'house', 'house', 'A1'),
  ('puerta', 'door', 'house', 'A1'),
  ('ventana', 'window', 'house', 'A1'),
  ('cocina', 'kitchen', 'house', 'A1'),
  ('baño', 'bathroom', 'house', 'A1'),
  ('habitación', 'room', 'house', 'A1'),
  ('cama', 'bed', 'house', 'A1'),
  ('mesa', 'table', 'house', 'A1'),
  ('silla', 'chair', 'house', 'A1'),
  ('sofá', 'sofa', 'house', 'A2'),
  ('espejo', 'mirror', 'house', 'A2'),
  ('llave', 'key', 'house', 'A2'),
  ('techo', 'roof, ceiling', 'house', 'A2'),
  ('suelo', 'floor, ground', 'house', 'A2'),
  ('ciudad', 'city', 'city', 'A1'),
  ('calle', 'street', 'city', 'A1'),
  ('plaza', 'square', 'city', 'A2'),
  ('tienda', 'shop', 'city', 'A1'),
  ('mercado', 'market', 'city', 'A1'),
  ('banco', 'bank, bench', 'city', 'A1'),
  ('hospital', 'hospital', 'city', 'A1'),
  ('escuela', 'school', 'city', 'A1'),
  ('iglesia', 'church', 'city', 'A2'),
  ('parque', 'park', 'city', 'A1'),
  ('coche', 'car', 'transport', 'A1'),
  ('tren', 'train', 'transport', 'A1'),
  ('avión', 'aeroplane', 'transport', 'A1'),
  ('autobús', 'bus', 'transport', 'A1'),
  ('bicicleta', 'bicycle', 'transport', 'A1'),
  ('barco', 'boat, ship', 'transport', 'A2'),
  ('camión', 'lorry, truck', 'transport', 'A2'),
  ('billete', 'ticket', 'transport', 'A2'),
  ('sol', 'sun', 'nature', 'A1'),
  ('luna', 'moon', 'nature', 'A1'),
  ('estrella', 'star', 'nature', 'A1'),
  ('cielo', 'sky', 'nature', 'A1'),
  ('árbol', 'tree', 'nature', 'A1'),
  ('flor', 'flower', 'nature', 'A1'),
  ('río', 'river', 'nature', 'A1'),
  ('mar', 'sea', 'nature', 'A1'),
  ('montaña', 'mountain', 'nature', 'A1'),
  ('playa', 'beach', 'nature', 'A1'),
  ('bosque', 'forest', 'nature', 'A2'),
  ('fuego', 'fire', 'nature', 'A2'),
  ('lluvia', 'rain', 'weather', 'A1'),
  ('nieve', 'snow', 'weather', 'A1'),
  ('viento', 'wind', 'weather', 'A1'),
  ('nube', 'cloud', 'weather', 'A2'),
  ('calor', 'heat', 'weather', 'A1'),
  ('frío', 'cold', 'weather', 'A1')
on conflict (spanish) do nothing;
